name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
   my_build_job:
      runs-on: ubuntu-latest
      steps: 
         -uses: action
         
run-name: npm install,test and build
 run:|
           npm install
           npm run build
   
